/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pk.labs.Lab9.ui;

import pk.labs.Lab9.beans.*;

import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author mikus
 */
public class MainFrame extends javax.swing.JFrame {
    
    private ConsultationList consultationList;

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        consultationListTableModel1 = new pk.labs.Lab9.models.ConsultationListTableModel();
        newConsultationPanel = new javax.swing.JPanel();
        consultationPanel = new pk.labs.Lab9.ui.ConsultationPanel();
        addConsultationButton = new javax.swing.JButton();
        consultationListPanel = new pk.labs.Lab9.ui.ConsultationListPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        newConsultationPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Szczegóły konsultacji"));

        addConsultationButton.setText("Dodaj");
        addConsultationButton.setName("addConsultation"); // NOI18N
        addConsultationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addConsultationButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout newConsultationPanelLayout = new javax.swing.GroupLayout(newConsultationPanel);
        newConsultationPanel.setLayout(newConsultationPanelLayout);
        newConsultationPanelLayout.setHorizontalGroup(
            newConsultationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(consultationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
            .addGroup(newConsultationPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(addConsultationButton))
        );
        newConsultationPanelLayout.setVerticalGroup(
            newConsultationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newConsultationPanelLayout.createSequentialGroup()
                .addComponent(consultationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addConsultationButton)
                .addContainerGap())
        );

        consultationPanel.setName("consultation"); // NOI18N
        consultationListPanel.setName("consultationList"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newConsultationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(consultationListPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newConsultationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(consultationListPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addConsultationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addConsultationButtonActionPerformed
        Consultation cons = this.consultationPanel.getConsultation();
        try {
            this.consultationList.addConsultation(cons);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.consultationListPanel.setConsultationList(this.consultationList);
    }//GEN-LAST:event_addConsultationButtonActionPerformed

    public void setConsultationList(ConsultationList consultationList) {
        this.consultationList = consultationList;
        consultationListPanel.setConsultationList(consultationList);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addConsultationButton;
    private pk.labs.Lab9.ui.ConsultationListPanel consultationListPanel;
    private pk.labs.Lab9.models.ConsultationListTableModel consultationListTableModel1;
    private pk.labs.Lab9.ui.ConsultationPanel consultationPanel;
    private javax.swing.JPanel newConsultationPanel;
    // End of variables declaration//GEN-END:variables
}
