/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pk.labs.Lab9.ui;

import java.text.SimpleDateFormat;
import pk.labs.Lab9.beans.ConsultationList;

/**
 *
 * @author mikus
 */
public class ConsultationListPanel extends javax.swing.JPanel {
    
    private ConsultationList consultationList;

    /**
     * Creates new form ConsultationListPanel
     */
    public ConsultationListPanel() {
        initComponents();
        DateRenderer dr = new DateRenderer(new SimpleDateFormat());
        consultationsTable.getColumn("Początek").setCellRenderer(dr);
        consultationsTable.getColumn("Koniec").setCellRenderer(dr);
        ButtonCell bc = new ButtonCell();
        consultationsTable.getColumn("Akcja").setCellRenderer(bc);
        consultationsTable.getColumn("Akcja").setCellEditor(bc);
    }
    
    public void setConsultationList(ConsultationList consultationList) {
        this.consultationList = consultationList;
        consultationListTableModel.setConsultations(consultationList);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        consultationListTableModel = new pk.labs.Lab9.models.ConsultationListTableModel();
        jScrollPane1 = new javax.swing.JScrollPane();
        consultationsTable = new javax.swing.JTable();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Lista konsultacji"));

        consultationsTable.setModel(consultationListTableModel);
        consultationsTable.setName("consultations"); // NOI18N
        jScrollPane1.setViewportView(consultationsTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private pk.labs.Lab9.models.ConsultationListTableModel consultationListTableModel;
    private javax.swing.JTable consultationsTable;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
